name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: if [ -if "main_py" ]; then
        echo "True"
        else
        echo "False"
        fi
      - run: echo hello world
