name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ ! -f "main.py" ]; then
            echo "main.py does not exist"
            exit 1
          fi
      - run: |
          python main.py
