name: CI

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python main.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-v${{ github.run_id }}.${{ github.run_number }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release created from tag ${{ github.ref_name }}.
            Attempt ${{ github.run_attempt }}
          draft: false
          prerelease: false
